// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3iv3d6s7vS2p_wzJjxmtKg6EUnNMgn3s',
    appId: '1:34379509505:web:07ae8f028100c0c8fa7500',
    messagingSenderId: '34379509505',
    projectId: 'gymgram-edc91',
    authDomain: 'gymgram-edc91.firebaseapp.com',
    storageBucket: 'gymgram-edc91.appspot.com',
    measurementId: 'G-DW574V3F2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqfFE-YLM3pEdzLMQVT3NTgCM9IAHAcFU',
    appId: '1:34379509505:android:f23197aeabdf3927fa7500',
    messagingSenderId: '34379509505',
    projectId: 'gymgram-edc91',
    storageBucket: 'gymgram-edc91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfw22Z4wPnJZmYMNjVmeNN_nYYVsW37g',
    appId: '1:34379509505:ios:567dd75d6d5d174dfa7500',
    messagingSenderId: '34379509505',
    projectId: 'gymgram-edc91',
    storageBucket: 'gymgram-edc91.appspot.com',
    androidClientId: '34379509505-l5kstddrjd9a8q85f02on0tqbod1jcb1.apps.googleusercontent.com',
    iosClientId: '34379509505-10b4piv3rno9h2fpngdbhshfj3goc260.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymGram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBfw22Z4wPnJZmYMNjVmeNN_nYYVsW37g',
    appId: '1:34379509505:ios:567dd75d6d5d174dfa7500',
    messagingSenderId: '34379509505',
    projectId: 'gymgram-edc91',
    storageBucket: 'gymgram-edc91.appspot.com',
    androidClientId: '34379509505-l5kstddrjd9a8q85f02on0tqbod1jcb1.apps.googleusercontent.com',
    iosClientId: '34379509505-10b4piv3rno9h2fpngdbhshfj3goc260.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymGram',
  );
}
